# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sergei/Data/src/probe-fibers

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sergei/Data/src/probe-fibers

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergei/Data/src/probe-fibers/CMakeFiles /home/sergei/Data/src/probe-fibers//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergei/Data/src/probe-fibers/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fibers_bin

# Build rule for target.
fibers_bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fibers_bin
.PHONY : fibers_bin

# fast build rule for target.
fibers_bin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fibers_bin.dir/build.make CMakeFiles/fibers_bin.dir/build
.PHONY : fibers_bin/fast

src/execucion_context_switch.o: src/execucion_context_switch.S.o
.PHONY : src/execucion_context_switch.o

# target to build an object file
src/execucion_context_switch.S.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fibers_bin.dir/build.make CMakeFiles/fibers_bin.dir/src/execucion_context_switch.S.o
.PHONY : src/execucion_context_switch.S.o

src/fiber.o: src/fiber.c.o
.PHONY : src/fiber.o

# target to build an object file
src/fiber.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fibers_bin.dir/build.make CMakeFiles/fibers_bin.dir/src/fiber.c.o
.PHONY : src/fiber.c.o

src/fiber.i: src/fiber.c.i
.PHONY : src/fiber.i

# target to preprocess a source file
src/fiber.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fibers_bin.dir/build.make CMakeFiles/fibers_bin.dir/src/fiber.c.i
.PHONY : src/fiber.c.i

src/fiber.s: src/fiber.c.s
.PHONY : src/fiber.s

# target to generate assembly for a file
src/fiber.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fibers_bin.dir/build.make CMakeFiles/fibers_bin.dir/src/fiber.c.s
.PHONY : src/fiber.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fibers_bin.dir/build.make CMakeFiles/fibers_bin.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fibers_bin.dir/build.make CMakeFiles/fibers_bin.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fibers_bin.dir/build.make CMakeFiles/fibers_bin.dir/src/main.c.s
.PHONY : src/main.c.s

src/scheduler.o: src/scheduler.c.o
.PHONY : src/scheduler.o

# target to build an object file
src/scheduler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fibers_bin.dir/build.make CMakeFiles/fibers_bin.dir/src/scheduler.c.o
.PHONY : src/scheduler.c.o

src/scheduler.i: src/scheduler.c.i
.PHONY : src/scheduler.i

# target to preprocess a source file
src/scheduler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fibers_bin.dir/build.make CMakeFiles/fibers_bin.dir/src/scheduler.c.i
.PHONY : src/scheduler.c.i

src/scheduler.s: src/scheduler.c.s
.PHONY : src/scheduler.s

# target to generate assembly for a file
src/scheduler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fibers_bin.dir/build.make CMakeFiles/fibers_bin.dir/src/scheduler.c.s
.PHONY : src/scheduler.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fibers_bin"
	@echo "... src/execucion_context_switch.o"
	@echo "... src/fiber.o"
	@echo "... src/fiber.i"
	@echo "... src/fiber.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/scheduler.o"
	@echo "... src/scheduler.i"
	@echo "... src/scheduler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

